# UCAD example API test http requests

### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMDgsInVzZXJuYW1lIjoic3V2aSIsInVzZXJfbGV2ZWxfaWQiOjEsImlhdCI6MTc2NDQzMDUwNCwiZXhwIjoxNzY0NTE2OTA0fQ.DwBOc6a2U0-bd-dKWAIMyeI41MgrjAat9PTqC2Km_Dk

### Get server root
GET http://localhost:3000/


## /media resource

### GET all media items
GET http://localhost:3000/api/media

### GET media item by id
GET http://localhost:3000/api/media/9590

### GET media items by user (logged in)
GET http://localhost:3000/api/media/user/
Authorization: Bearer {{token}}

### POST new media item
POST http://localhost:3000/api/media
Authorization: Bearer {{token}}
content-type: application/json

{
  "filename": "kuva.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}

### POST new media item including media file
POST http://localhost:3000/api/media
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./test-cat.png
------Boundary--

### Update existing media item
PUT http://localhost:3000/api/media/9590
content-type: application/json

{
  "title": "New title",
  "description": "Some new description"
}

### Delete your own media item
DELETE http://localhost:3000/api/media/2
Authorization: Bearer {{token}}

#####################

## /users resource

### GET /users
GET http://localhost:3000/api/user

### GET user by id
GET http://localhost:3000/api/user/260

### Add new user
POST http://localhost:3000/api/user
content-type: application/json

{
  "username": "suvi",
  "password": "kalakana",
  "email": "suvi1@example.com"
}

### Login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "suvi",
  "password": "kalakana"
}

### Auth GET me
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{token}}

### Update existing user
PUT http://localhost:3000/api/user/305
content-type: application/json

{
  "username": "New Username"
}

### Delete user
DELETE http://localhost:3000/api/user/3
Authorization: Bearer {{token}}

#####################

## /likes resource

### GET likes by media
GET http://localhost:3000/api/likes/media/1

### GET likes by user
GET http://localhost:3000/api/likes/user/2

### POST add new like
POST http://localhost:3000/api/likes
Content-Type: application/json

{
  "user_id": 2,
  "media_id": 1
}

### DELETE like
DELETE http://localhost:3000/api/likes/3
Authorization: Bearer {{token}}