# UCAD example API test http requests

### Get server root
GET http://localhost:3000/


## /media resource

### GET all media items
GET http://localhost:3000/api/media

### GET media item by id
GET http://localhost:3000/api/media/9590

### Add new media item
POST http://localhost:3000/api/media
content-type: application/json

{
  "filename": "kuva.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}

### Update existing media item
PUT http://localhost:3000/api/media/9590
content-type: application/json

{
  "title": "New title",
  "description": "Some new description",
}

### Delete media item
DELETE http://localhost:3000/api/media/9590

#####################

## /users resource

### GET /users
GET http://localhost:3000/api/user

### GET user by id
GET http://localhost:3000/api/user/260

### Add new user
POST http://localhost:3000/api/user
content-type: application/json

{
  "user_id": "305",
  "username": "New user",
  "password": "*******",
  "email": "email@example.com",
  "user_level_id": "1"
}

### Update existing user
PUT http://localhost:3000/api/user/305
content-type: application/json

{
  "username": "New Username"
}

### Delete user
DELETE http://localhost:3000/api/user/3